Cargo.lock, methods/Cargo.toml, methods/guest/Cargo.lock, methods/guest/Cargo.toml, relay/Cargo.toml, relay/src/lib.rs
Updates the zkvm dep to 0.16.1 by setting the branch to `release-0.16`. Also made the changes in .16 to use `LocalExecutor`.
=> Update risc0 zkvm to 0.16.1

script/BonsaiDeploy.sol
This PR follows up from https://github.com/risc0/risc0/pull/813 to make the Control_ID parameters configurable in the constructor.
Closes: https://github.com/risc0/bonsai-foundry-template/issues/46
=> Make Control ID Parameterized

deployment-guide.md, relay/examples/offchain_request.rs, tests/BonsaiStarter.t.sol, tests/BonsaiStarterLowLevel.t.sol
Adds an error message when a BONSAI_API_KEY is not defined when using the off-chain example
=> Enforce BONSAI_API_KEY usage

README.md
Some minor link-changes to make the bonsai foundry template more cleanly integrate with our easiest-to-use reference materials on the dev docs site. 
Feel free to close this if you'd rather wait until after landing the changes you're working on.
=> improving dev docs pointers

README.md, cli/src/interface.rs, contracts/README.md, deployment-guide.md, methods/README.md, script/Deploy.s.sol, sdk/src/cli.rs, sdk/src/eth.rs
- edits on readthrough of readme
- changes to deployment guide in the process of testing it out
- fix error leftover from working on the guest interface
- quick pass on other md files
=> Another round of suggestions for the new no-relay template

.cargo/config.toml, Cargo.lock, Cargo.toml, README.md, methods/Cargo.toml, methods/build.rs, methods/src/lib.rs
Here is a batch of suggsted changes to the WIP no-relay branch
- simplify config and remove deprecated lint
- use executor in tests
- fix up build and use local clone of risc0-ethereum
=> Suggestions for no-relay template on Feb 15

remappings.txt
As far as I've understood, remappings of `risc0-ethereum` should be replicated to the foundry template as well, so `murky` has been added to that.
Closes https://github.com/risc0/risc0-ethereum/issues/25
=> Add murky to remappings

Cargo.toml
Version 0.9 of the crates in the `risc0-ethereum` repository is being released. The major feature is a new library to make Ethereum view calls within the guest.
This PR bumps the reference to the `risc0-ethereum` repo to the `release-0.9` branch.
https://github.com/risc0/risc0-ethereum
=> Bump risc0-ethereum dependencies to 0.9

deployment-guide.md
Accidentally, I've removed the deployment guide with https://github.com/risc0/risc0-foundry-template/pull/95
=> Revert deployment guide deletion

README.md
Clarification specifically around stark2snark support on apple silicon. Specifically, similar to [#1952](https://github.com/risc0/risc0/pull/1952). 
This was a major issue for some users on the Discord recently (see [here](https://discord.com/channels/953703904086994974/1243250690344751227/1244567425349849138) and [here](https://discord.com/channels/953703904086994974/953703904086994977/1241971552312889396)) so extra clarification was needed.
=> add clarification regarding apple silicon support and links to relevant issues

README.md
Noticed a broken link to where the dev can install Docker.
=> Fix broken link to Docker

deployment-guide.md, script/Deploy.s.sol, script/config.toml
I went ahead and implemented some suggested changes to the mainnet deployment scripts in https://github.com/risc0/risc0-foundry-template/pull/119
I also tested this by using the provided commands to depploy to Mainnet. Deployment works! I did not test posting the transaction to set the even number yet. I will do that this afternoon.
=> Suggestions for PR #119

.gitmodules
https://stackoverflow.com/questions/8044583/how-can-i-move-a-tag-on-a-git-branch-to-a-different-commit states we cannot use tags, so this branch = tag is broken.
Instead of updating here, we will manage commits for sub-modules manually and locked into the tags/releases for known working versions (in #124)
=> Remove incorrect branch on .gitmodules

.github/workflows/linear.yml
Simmilar to in other repos, this PR adds a GitHub Actions workflow to find or create a Linear issue when a PR is created
Related to https://github.com/risc0/risc0-ethereum/pull/182
=> WEB3-49: Add workflow to find or create Linear issue from PR

README.md
- updated old instructions in README.md with `rzup` to install `cargo risczero`.
=> WEB3-65: replaced old installation instructions with rzup

.github/workflows/main.yml, Cargo.lock, Cargo.toml, apps/Cargo.toml, apps/src/bin/publisher.rs, contracts/EvenNumber.sol, contracts/IEvenNumber.sol, methods/guest/Cargo.lock, methods/guest/Cargo.toml, rust-toolchain.toml, script/Deploy.s.sol
- Bump dependencies
- Replace `ethers` with `alloy`
- Add `IEvenNumber.sol` interface to simplify the interaction of the publisher
=> WEB3-76: Bump risc0-ethereum and risc0-zkvm

methods/README.md
I found a couple of broken links using `git ls-files '*.md' | xargs lychee --base . --cache --`. This PR fixes them and additionally formats the modified .md file.
=> WEB3-155: Fix two broken links in `methods/README.md`

README.md
In order to make sure local foundry deps are up-to-date, `git submodule update --init` should be ran
=> WEB3-206: Add git submodule update --init to README

methods/build.rs
added to `methods/build.rs`:
```rust
run_git_submodule_update();
println!("cargo:rerun-if-changed=.gitmodules");
```
to automatically keep local libraries up to date on build.
=> WEB3-207: add git submodule --init to methods/build.rs

Cargo.lock, apps/Cargo.toml
Reported by a user, Bonsai support in `default_prover` was gated behind the `bonsai` feature flag in a recent release. Although included in `default` features, this was not enabled in the apps folder. As a result, setting the `BONSAI_API_KEY` env var does not enable Bonsai on `main` right now.
=> WEB3-324: Use default-features in risc0-zkvm in apps to fix Bonsai support

.github/workflows/main.yml, .gitmodules, Cargo.lock, Cargo.toml, apps/src/bin/publisher.rs, methods/build.rs, methods/guest/Cargo.lock, methods/guest/Cargo.toml, remappings.txt, rust-toolchain.toml
This PR also drops both `forge-std` and `openzeppelin-contracts` submodules, and uses the ones from `risc0-ethereum` instead
=> WEB3-396: Updates for v2.0.0
